services:
  - type: web
    name: discord-afk-bot
    env: node
    buildCommand: npm install && pip install gtts
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
